# -*- coding: utf-8 -*-
"""name_printer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5GIy-enqaWb0MoyCoTL9ADZA7v8FOtP
"""

# CS175
# Maggie Volker

print("+--------+")
print("| Maggie |")
print("+--------+")